version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::158170262426:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-ZHUWDTFS6WJT"
permissions_provider = "AWS IAM"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::158170262426:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-133N7MJHJ9ZQG"
cloudformation_execution_role = "arn:aws:iam::158170262426:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1DFZP3NLM7HX3"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-v2pj2sn3vmro"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::158170262426:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-OYUYQ27EVHGG"
cloudformation_execution_role = "arn:aws:iam::158170262426:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-19COCI3ME16GV"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1knvaa3845n0f"
image_repository = ""
region = "us-east-1"
